name: Deploy Prebuilt Java JAR to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy prebuilt JAR to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ben-ora-java-client2
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: jar/app.jar  # Update to correct relative path if needed
